# Generated by Django 3.2.7 on 2023-04-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyviews',
            old_name='particular_property',
            new_name='property',
        ),
    ]
